mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('mysite.views',
    url(r'^$', 'index'),
    url(r'^client/', 'client'),
    url(r'^theory/', 'theory'),
    # url(r'^background/', 'background'),
    url(r'^tutorial/', 'tutorial'),
    url(r'^about/', 'about'),
    url(r'^api/', include('wirm.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

mysite/wirm/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.urlpatterns import format_suffix_patterns
from wirm import views

urlpatterns = patterns('wirm.views',
    url(r'^$', 'api_root'),
    url(r'^parameters/$', views.ParameterList.as_view(), name='parameters-list'),
    url(r'^parameters/(?P<pk>[0-9]+)$', views.ParameterDetail.as_view(), name='parameter-detail'),
    url(r'^projects/$', views.ProjectList.as_view(), name='projects-list'),
    url(r'^projects/(?P<pk>[0-9]+)$', views.ProjectDetail.as_view(), name='project-detail'),
    url(r'^projects/(?P<project_pk>[0-9]+)/comments/$', views.ProjectCommentList.as_view(), name='project-comment-list'),
    url(r'^projects/(?P<project_pk>[0-9]+)/comments/(?P<pk>[0-9]+)$', views.ProjectCommentDetail.as_view(), name='project-comment-detail'),
    url(r'^users/$', views.UserList.as_view(), name='users-list'),
    url(r'^users/(?P<pk>[0-9]+)$', views.UserDetail.as_view(), name='user-detail'),
    url(r'^comments/$', views.CommentList.as_view(), name='comments-list'),
    url(r'^comments/(?P<pk>[0-9]+)$', views.CommentDetail.as_view(), name='comment-detail'),
)

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += patterns('',
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
)

mysite/wirm/models.py
from django.db import models
from jsonfield import JSONField


class Parameter(models.Model):
    PARAMETER_GROUP_CHOICES = (
        ('basic', 'Basic'),
        ('advanced', 'Advanced'),
    )
    key = models.CharField(blank=False, max_length=10)
    title = models.CharField(blank=False, max_length=50)
    units = models.CharField(max_length=20)
    value = models.FloatField()
    min = models.FloatField(default=0.0)
    max = models.FloatField()
    group = models.CharField(choices=PARAMETER_GROUP_CHOICES, default='basic', max_length=20)

    def __unicode__(self):
        return '%s (%s)' % (self.title, self.units)


class Project(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(default="New Project", blank=False, max_length=100)
    location = models.CharField(default="", blank=True, max_length=100)
    description = models.TextField()
    owner = models.ForeignKey('auth.User', related_name='projects')
    parameter_values = JSONField()

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    project = models.ForeignKey('Project', related_name='comments')
    owner = models.ForeignKey('auth.User', related_name='comments')
    created = models.DateTimeField(auto_now_add=True, default=None)
    comment = models.TextField(max_length=500)

    def __unicode__(self):
        return "%s: %s..." % (self.owner.username, self.comment[:50])

mysite/mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def client(request):
    return render(request, 'client.html')


def theory(request):
    return render(request, 'theory.html')


# def background(request):
#     return render(request, 'background.html')


def tutorial(request):
    return render(request, 'tutorial.html')


def about(request):
    return render(request, 'about.html')

mysite/wirm/views.py
from wirm.models import Project, Parameter, Comment
from wirm import serializers
from wirm.permissions import IsOwnerOrReadOnly
from rest_framework import generics
from rest_framework import permissions
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404


@api_view(('GET',))
def api_root(request, format=None):
    return Response({
        # 'users': reverse('users-list', request=request, format=format),
        'parameters': reverse('parameters-list', request=request, format=format),
        'projects': reverse('projects-list', request=request, format=format),
        'comments': reverse('comments-list', request=request, format=format),
    })


class ParameterList(generics.ListAPIView):
    """
    List all parameters.
    """
    model = Parameter
    serializer_class = serializers.ParameterSerializer


class ParameterDetail(generics.RetrieveAPIView):
    """
    Retrieve single parameter.
    """
    model = Parameter
    serializer_class = serializers.ParameterSerializer


class ProjectList(generics.ListCreateAPIView):
    """
    Lists saved projects or create new project for current authenticated user.
    """
    # queryset = Project.objects.all()
    serializer_class = serializers.ProjectSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def get_queryset(self):
        user = self.request.user
        if (user.is_anonymous()):
            return []
        return Project.objects.filter(owner=user)

    def pre_save(self, obj):
        obj.owner = self.request.user


class ProjectDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve, update or destroy a project.
    """
    queryset = Project.objects.all()
    serializer_class = serializers.ProjectSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly)


class UserList(generics.ListAPIView):
    """
    List all users.
    """
    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer


class UserDetail(generics.RetrieveAPIView):
    """
    Retrieve single user.
    """
    queryset = User.objects.all()
    serializer_class = serializers.UserDetailSerializer


class CommentList(generics.ListAPIView):
    """
    List all comments.
    """
    queryset = Comment.objects.all()
    serializer_class = serializers.CommentSerializer
    # permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class CommentDetail(generics.RetrieveAPIView):
    """
    Retrieve single comment.
    """
    queryset = Comment.objects.all()
    serializer_class = serializers.CommentSerializer
    # permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class ProjectCommentList(generics.ListCreateAPIView):
    """
    List all comments for a project.
    """
    serializer_class = serializers.CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def pre_save(self, obj):
        project_pk = self.kwargs['project_pk']
        obj.project = Project.objects.get(pk=project_pk)
        obj.owner = self.request.user

    def get_queryset(self):
        """
        This view should return a list of all comments for
        the project pk as determined by the project_pk portion of the URL.
        """
        project_pk = self.kwargs['project_pk']
        project = get_object_or_404(Project, pk=project_pk)
        return Comment.objects.filter(project__pk=project_pk)


class ProjectCommentDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    Retrieve single comment for a project.
    """
    serializer_class = serializers.CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly)

    def get_queryset(self):
        """
        This view should return a list of all comments for
        the project pk as determined by the project_pk portion of the URL.
        """
        project_pk = self.kwargs['project_pk']
        project = get_object_or_404(Project, pk=project_pk)
        queryset = project.comments.all()
        return queryset

mysite/templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock title %}

{% block content %}
<h1>About WIRM</h1>
<hr>
<div class="row row-doc">
  <div class="span3">
    <h3>Overview</h3>
  </div>
  <div class="span9">
    <p>The Web-based Interactive River Model (WIRM) was a part of a research project on web-based approaches to environmental modeling and decision support. It was primarily intended as a demonstration of modern web technologies for creating interactive visualizations and user interfaces for water quality simulation model. This research was being conducted by <a href="mailto:jeff@walkerenvres.com">Jeff Walker</a>, PhD Candidate, and <a href="mailto:steven.chapra@tufts.edu">Dr. Steve Chapra</a>, Professor in the <a href="http://engineering.tufts.edu/cee/">Dept. of Civil and Environmental Engineering</a> at <a href="http://www.tufts.edu">Tufts University</a>. For more information about this research and additional projects, visit <a href="http://phd.walkerenvres.com">phd.walkerenvres.com</a>.</p>
  </div>
</div>
<hr>
<div class="row row-doc">
  <div class="span3">
    <h3>Publication</h3>
  </div>
  <div class="span9">
    <p><a href="http://dx.doi.org/10.1016/j.envsoft.2014.01.023">Walker, J. D., and Chapra, S. C. (2014). A client-side web application for interactive environmental simulation modeling. <i>Environmental Modelling &amp; Software</i>, 55, 49-60</a></p>
  </div>
</div>
<hr>
<div class="row row-doc">
  <div class="span3">
    <h3>Purpose</h3>
  </div>
  <div class="span9">
    <p>Simulation models are widely used to support environmental management and decision making. However, most models require strong technical and programming skills due to antiquated or poorly designed user interfaces. This leaves decision makers and stakeholders reliant on modeling experts to develop, run and analyze models on their behalf.</p>
    <p>The World Wide Web has evolved into a new software platform for creating interactive, easy-to-use, and widely accessible applications. For many years, environmental modelers have been interested in developing web-based models and decision support systems that would improve model accessibility and understanding by decision makers and stakeholders. Performance gains in JavaScript engines (e.g. <a href="https://code.google.com/p/v8/">Chrome's V8</a>) as well as a diverse ecosystem of open-source JavaScript libraries (e.g. <a href="http://jquery.com">jQuery</a>, <a href="http://backbonejs.org">Backbone</a>, <a href="http://d3js.org">d3</a> to name a few) are capable of supporting client-based web applications for environmental simulation. WIRM demonstrates the use of these technologies to create a highly interactive, easy-to-use, and widely accessible application for water quality simulation.</p>
  </div>
</div>
<hr>
<div class="row row-doc">
  <div class="span3">
    <h3>Server Architecture</h3>
  </div>
  <div class="span9">
    <p>The WIRM server was built using the <a href="https://www.djangoproject.com/">Django</a> web framework, which is "a high-level Python Web framework that encourages rapid development and clean, pragmatic design." Django is a popular and mature framework that has been under active development for over many years.</p>
    <p>In addition, this site utilizes a number of Django plug-ins including:
    <ul>
      <li><a href="http://django-rest-framework.org/">Django Rest Framework</a>: for delivering a REST-based <a href="/api/">API</a> for accessing model parameters, projects, users and comments (<a href="https://github.com/tomchristie/django-rest-framework">License</a>)</li>
      <li><a href="https://bitbucket.org/ubernostrum/django-registration/">Registration</a>: user account registration and email-based activation (<a href="https://bitbucket.org/ubernostrum/django-registration/src/8f242e35ef7c004e035e54b4bb093c32bf77c29f/LICENSE?at=default">License</a>)</li>
    </ul>
    </p>
    <p>The source code for the server application is available on <a href="https://github.com/walkerjeffd/phd-wirm-server">GitHub</a>.</p>
  </div>
</div>
<hr>
<div class="row row-doc">
  <div class="span3">
    <h3>Client Architecture</h3>
  </div>
  <div class="span9">
    <p>The client-side web application controls the user interface, simulation engine and visualization renderer, all of which are executed within the web browser. It is built using a number of free and open-source software libaries including:
    <ul>
      <li><a href="http://jquery.com">jQuery</a>: DOM manipulation, AJAX communication (<a href="https://github.com/jquery/jquery/blob/master/MIT-LICENSE.txt">License</a>)</li>
      <li><a href="http://jqueryui.com/">jQuery-ui</a>: slider widgets (<a href="https://github.com/jquery/jquery-ui/blob/master/MIT-LICENSE.txt">License</a>)</li>
      <li><a href="http://backbonejs.org">Backbone.js</a>: MVC application framework (<a href="https://github.com/documentcloud/backbone/blob/master/LICENSE">License</a>)</li>
      <li><a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a>: front-end framework (<a href="https://github.com/twitter/bootstrap/blob/master/LICENSE">License</a>)</li>
      <li><a href="http://www.numericjs.com/">Numeric.js</a>: element-wise array operations (<a href="https://github.com/sloisel/numeric/blob/master/license.txt">License</a>)</li>
      <li><a href="http://d3js.org">d3.js</a>: data visualization (<a href="https://github.com/mbostock/d3/blob/master/LICENSE">License</a>)</li>
      <li><a href="http://underscore.org">Underscore.js</a>: miscellaneous JavaScript utilities (<a href="https://github.com/documentcloud/underscore/blob/master/LICENSE">License</a>)</li>
      <li><a href="http://www.mathjax.org/">MathJax.js</a>: equation rendering using Latex-style code (<a href="https://github.com/mathjax/MathJax/blob/master/LICENSE">License</a>)</li>
      <li><a href="http://momentjs.com/">Moment.js</a>: date/time formatting (<a href="https://github.com/timrwood/moment/blob/develop/LICENSE">License</a>)</li>
    </ul>
    </p>
    <p>The source code for the client application is available on <a href="https://github.com/walkerjeffd/phd-wirm-client">GitHub</a>.</p>
  </div>
</div>
<hr>
<div class="row row-doc">
  <div class="span3">
    <h3>Disclaimer</h3>
  </div>
  <div class="span9">
    <p>Use of this website is at your own risk and assumes acceptance of terms described in the <a href="http://ourdisclaimer.com/?i=WIRM">disclaimer</a>.</p>
  </div>
</div>

{% endblock content %}

mysite/templates/background.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Background{% endblock title %}

{% block content %}
<h1>Background</h1>
<p>Welcome to the Web-based Interactive River Model (WIRM), a web application created to demonstrate the use of modern web technologies for web-based simulation of environmental systems. The application was designed to provide a highly interactive simulation interface using only standard web technologies eliminating the need for third-party browser plug-ins (e.g. Java applets, Flash). Read more about the architecture of the website on the <a href="/about/">About</a> page.</p>
<hr>
<div class="row">
  <div class="span2">
    <h3>Modelling Process</h3>
  </div>
  <div class="span10">
    <h4>What are simulation models?</h4>
    <p>Simulation models are commonly used by scientists and engineers to study environmental systems such as lakes, rivers, forests, grasslands, etc. Some people might think of models as miniature versions of real systems (think model airplanes or model trains), and indeed, some researchers do create so-called physical models that are small-scale replicas of environmental systems. But environmental systems are incredibly complex, involving dynamic interactions between many physical, chemical, biological and even socioeconomic processes. Representing all of these complex processes in a physical model is virtually impossible, and so scientists and engineers use mathematical equations to represent these systems and processes.</p>
    <hr>
    <h4>Why use Simulation Models?</h4>
    While traditional scientific experiments are sometimes used to study environmental systems, oftentimes it is not feasible to perform experiments on real systems, especially large systems like entire watersheds or oceans. By using simulation models, scientists and engineers can study the behavior of environmental systems using so-called "numerical experiments." Once a model is created and tested, it can be used to study what happens when parts of the system are changed. For example, a model of a watershed can be used to predict what will happen to the amount of streamflow when rainfall patterns change due to climate change, and what might those changes do to the native fish populations.</p>
    <hr>
    <h4>How are simulation models used to make decisions?</h4>
    <p>Simulation models allow scientists and engineers to investigate "what if" scenarios, helping us better understand what effects humans are having on environmental systems and what management actions or policies would be most effective in reducing our impacts and protecting these important ecosystems.</p>
    <p>Management decisions for water quality problems are primarily based on the question: how much of a given pollutant can be discharged to a waterbody without having unacceptable negative impacts? This question is often answered by using a simulation model that let's the user lower the amount of pollution until it has a minimal (or acceptable) impact.</p>
  </div>
</div>
<hr>
<div class="row">
  <div class="span2">
    <h3>Scientific Background</h3>
  </div>
  <div class="span10">
    <p>The WIRM application simulates the effect of wastewater discharge (or similar types of <a href="http://en.wikipedia.org/wiki/Point_source_pollution">point source pollution</a>) on dissolved oxygen levels in rivers and streams. The underlying mathematical model is derived from one of the first water quality models known as the <a href="http://en.wikipedia.org/wiki/Streeter-Phelps_equation">Streeter-Phelps model</a> dating back to a study on the Ohio River in the 1925. This model was instrumental in understanding the effect of wastewater discharge on dissolved oxygen concentrations in rivers.</p>
  </div>
</div>

{% endblock content %}

mysite/templates/client.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Client{% endblock title %}

{% block head_scripts %}
  <script type="text/javascript">
    if (!window.console) console = {log: function() {}};
  </script>
  <script src="{% static "js/lib/modernizr.custom.92887.js" %}"></script>
{% endblock head_scripts %}

{% block content %}

<div class="container text-center">
<h1>Loading...</h1>
<img src="{% static "img/ajax-loader.gif" %}" width="31" height="31"></img>
</div>

<script type="text/template" id="template-loading">
<div class="container text-center">
<h1>Loading...</h1>
<img src="{% static "img/ajax-loader.gif" %}" width="31" height="31"></img>
</div>
</script>


<script type="text/template" id="template-dashboard">
<div class="row" id="dashboard-header">
  <div class="span6" id="project-info">
  </div>
  <div class="span6" id="controls">
  </div>
</div>
<div class="row">
  <div class="span6" id="chart-container">
  </div>
  <div class="span6" id="tabs-container">
  </div>
</div>
</script>

<script type="text/template" id="template-project-info">
<h1 id="project-title"><%= title %></h1>
<div id="project-details" style="position:relative;">
  <ul class="project-info-list">
    <li><strong>Location</strong>: <%= location %></li>
    <li><strong>Description</strong>: <%= description %></li>
  </ul>
  <div class="btn-toolbar">
    <div class="btn btn-edit"><i class="icon-edit"></i> Edit Project Info</div>
    <div class="btn btn-danger btn-delete"><i class="icon-trash icon-white"></i> Delete Project</div>
  </div>
  <div class="alert alert-error" style="position:absolute; left:147px;">
    <span>Are you sure?</span>
    <div class="btn btn-danger btn-confirm">Yes</div>
    <div class="btn btn-cancel">No</div>
  </div>
</div>
</script>

<script type="text/template" id="template-controls">
<div class="btn-toolbar">
  <div class="btn btn-primary btn-save"><i class="icon-check icon-white"></i> Save</div>
  <div class="btn btn-reset"><i class="icon-refresh"></i> Reset</div>
  <div class="btn btn-share btn-info pull-right"><i class="icon-share icon-white"></i> Share</div>
</div>
<div class="alert">
  <span id="status"></span>
</div>
</script>

<script type="text/template" id="template-share">
<div id="shareModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="shareModalLabel">Share project</h3>
  </div>
  <div class="modal-body">
    <p>To share this project, simply send this URL to your colleagues.</p>
    <input type="text" class="input-xlarge" value="<%= url %>">
  </div>
  <div class="modal-footer">
    <button class="btn btn-close" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>
</script>

<script type="text/template" id="template-project-modal">
<div id="projectModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="projectModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="projectModalLabel">Create Project</h3>
  </div>
  <div class="modal-body">
    <div class="alert alert-error"></div>
    <p><label for="id_title">Title:</label> <input class="input-xlarge" name="title" type="text" id="id_title" value="<%=title%>"></p>
    <p><label for="id_location">Geographic Location:</label> <input class="input-xlarge" name="location" type="text" id="id_location" value="<%=location%>"></p>
    <p><label for="id_description">Description:</label> <textarea class="input-xlarge" cols="150" rows="5" name="description" id="id_description"><%=description%></textarea></p>
  </div>
  <div class="modal-footer">
    <button class="btn btn-close" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary btn-save">Save</button>
  </div>
</div>
</script>

<script type="text/template" id="template-comment-tab">
<form class="form-inline">
  <input name="comment" type="text" id="id_comment" placeholder="Enter your comment...">
  <button id="submit-comment" class="btn btn-primary">Submit</button>
</form>
<div class="comment-list-container"></div>
</script>

<script type="text/template" id="template-parameter-label">
  <span class="param-label"><%= title %> (<%= units %>)</span>: <span class="param-value"><%= value %></span>
  <a href="/theory/#<%= key %>" target="_blank" class="btn btn-mini btn-success param-help">Help</a>
</script>

<script type="text/template" id="template-project-container">
<h1>Saved Projects</h1>
</script>

<script type="text/template" id="template-project-item">
<hr>
<h4><a href="/client/#projects/<%= id %>"><%= title %></a></h4>
<ul>
  <li>Location: <%= location %></li>
  <li>Description: <%= description %></li>
  <li>Created: <%= created %> (<%= createdFromNow %>)</li>
  <li>Updated: <%= updated %> (<%= updatedFromNow %>)</li>
</ul>
<div class='project-buttons' style="position:relative">
  <a class="btn btn-small btn-success btn-load" href="#projects/<%= id %>"><i class="icon-circle-arrow-right icon-white"></i> Load</a>
  <button class="btn btn-small btn-danger btn-delete"><i class="icon-trash icon-white"></i> Delete</button>
  <div class="alert alert-error" style="display:none; margin-top:10px; position:absolute; left:0px;">
    <span>Are you sure?</span>
    <div class="btn btn-danger btn-confirm">Yes</div>
    <div class="btn btn-cancel">No</div>
  </div>
</div>
</script>


<script type="text/template" id="template-error">
<h1><%= title %></h1>
<p><%= message %></p>
</script>

<script type="text/template" id="template-tabs">
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#tab-param-basic" data-toggle="tab">Basic</a>
  </li>
  <li>
    <a href="#tab-param-advanced" data-toggle="tab">Advanced</a>
  </li>
  <li>
    <a href="#tab-comments" data-toggle="tab">Comments</a>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade active in" id="tab-param-basic"></div>
  <div class="tab-pane fade in" id="tab-param-advanced"></div>
  <div class="tab-pane fade in" id="tab-comments"></div>
</div>
</script>

<script type="text/template" id="template-comment-item">
<div class="comment-header">
  <span class="comment-owner"><%= owner.username %></span> • 
  <span class="comment-time"><%= formatCreated %></span>
  <button class="btn btn-mini btn-delete btn-danger" style="float:right;"><i class="icon-trash icon-white"></i> Delete</button>
</div>
<div class="comment-text"><%= comment %></div>
<hr>
</script>

{% endblock content %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static "js/lib/underscore-1.4.4.js" %}"></script>
  <script src="{% static "js/lib/backbone-1.0.0.js" %}"></script>
  <script src="{% static "js/lib/d3-3.0.8.js" %}"></script>
  <script src="{% static "js/lib/numeric-1.2.6.js" %}"></script>
  <script src="{% static "js/lib/moment-2.0.0.js" %}"></script>
  <script src="{% static "js/wirm-0.9.3.js" %}"></script>
    

  <script>
  $(function() {
    {% if user.is_authenticated %}
      App.user = "{{ user }}";
    {% else %}
      App.user = null;
    {% endif %}
    if (Modernizr.svg) {
      App.boot($('#content'));  
    } else {
      $('#content').html('<div class="alert alert-danger"><h1>Error!</h1><p>Your browser does not support SVG graphics, which are required for this application. Please upgrade to the latest version of Internet Explorer, Chrome, Firefox, Safari, or Opera. The latest version of <a href="http://www.google.com/chrome">Chrome</a> is recommended for optimal performance.</p></div>');
    };
    
  });
  </script>
{% endblock scripts %}

mysite/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="hero-unit" style="position:relative;">
  <h1>Web-based Interactive River Model (WIRM)</h1>
  <img src="{% static "img/chart.png" %}" alt="Chart" width="907" height="320" style="align:center;">
  <br><br>
  <p>A simple water quality model for understanding the effects of pollution on dissolved oxygen levels in rivers and streams.</p>
  <p><a href="/client/" class="btn btn-primary btn-large">Try it! &raquo;</a></p>
</div>

<div class="row">
  <div class="span3">
    <h2>Sign Up</h2>
    <p>Register for free to save model configurations on the server.</p>
    <p><a class="btn" href="/accounts/register/">Sign up &raquo;</a></p>
  </div>
  <div class="span3">
    <h2>Theory</h2>
    <p>Read about the theory, equations, and parameters used in the model.</p>
    <p><a class="btn" href="/theory/">Theory &raquo;</a></p>
  </div>
  <div class="span3">
    <h2>Tutorial</h2>
    <p>Follow the tutorial to learn more about to use the WIRM interface.</p>
    <p><a class="btn" href="/tutorial/">Tutorial &raquo;</a></p>
  </div>
  <div class="span3">
    <h2>Model</h2>
    <p>After reading the theory and tutorial, start modeling...</p>
    <p><a class="btn" href="/client/">Start Modeling &raquo;</a></p>
  </div>  
</div>
{% endblock content %}